---

- name: Install git
  yum: name=git state=installed

- name: Install nginx
  yum: name=nginx state=installed

- name: Create directory where put logs
  file: path={{ log_dir }} owner={{ web_user }} group={{ web_group }} state=directory
