language: python
python:
  - 3.5

sudo: false

install:
  - pip install -r requirements_dev.txt
  - nvm install 5.1.1
  - npm install

script:
  - pre-commit run --all-files
  - python -m src.test_api
  - npm test
  - npm run build
